# Generated by Django 3.0.8 on 2020-11-08 14:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_auto_20201108_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dob',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 11, 8, 19, 49, 38, 947775)),
        ),
    ]
