# Generated by Django 3.0.8 on 2020-11-08 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0007_auto_20201108_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
